# Generated by Django 5.2.7 on 2025-10-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gravacoes',
            old_name='paciente',
            new_name='motoristas',
        ),
    ]
